# Generated by Django 4.1.1 on 2022-12-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitblog', '0003_post_created_on_alter_post_title_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
