# Generated by Django 4.1.1 on 2022-12-16 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitblog', '0004_alter_post_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_on',
        ),
    ]
