# Generated by Django 4.1.1 on 2022-12-13 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('workout', 'Workout routine'), ('food_recipe', 'Food Recipes'), ('equipment', 'Equipment'), ('motivation', 'Motivation'), ('other', 'Other')], max_length=30)),
                ('tag_title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
